project_id = "zkkndhebaefxyuuvpobn"

[functions.analyze-business-idea]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = true

[functions.send-admin-notification]
verify_jwt = true

[functions.generate-logos]
verify_jwt = true